"""End-to-end test: run the griffe-backed emitter over a tiny synthetic package
and assert the emitted MDX uses the frozen component contract and that the
inventory has the expected entries.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pytest

from bloqade_docs_emit_python.emitter import Config, Emitter

PKG_INIT = '"""My package.\n\nLonger package description.\n"""\n'

CORE_SRC = textwrap.dedent('''\
    """Core module.

    A longer description that lives in the module body.
    """

    GREETING = "hello"


    def greet(name: str, times: int = 1) -> str:
        """Greet someone.

        Args:
            name: Who to greet.
            times: How many times to repeat the greeting.

        Returns:
            The assembled greeting string.

        Raises:
            ValueError: If ``times`` is negative.
        """
        if times < 0:
            raise ValueError("times must be >= 0")
        return ("hi " * times) + name


    def _hidden() -> None:
        """A private module-level function that must NOT be emitted."""


    class Widget:
        """A widget.

        Attributes:
            size: The widget size in pixels.
        """

        def __init__(self, size: int) -> None:
            """Create a widget.

            Args:
                size: Initial size in pixels.
            """
            self.size = size

        def area(self) -> int:
            """Compute the area.

            Returns:
                The area value.
            """
            return self.size * self.size

        @property
        def doubled(self) -> int:
            """The doubled size."""
            return self.size * 2

        def _secret(self) -> None:
            """A private method that must NOT be emitted."""
    ''')


@pytest.fixture()
def emitted(tmp_path):
    pkg = tmp_path / "mypkg"
    pkg.mkdir()
    (pkg / "__init__.py").write_text(PKG_INIT, encoding="utf-8")
    (pkg / "core.py").write_text(CORE_SRC, encoding="utf-8")

    out = tmp_path / "out"
    cfg = Config(
        package="mypkg",
        src=str(pkg),
        repo="owner/repo",
        ref="v1.0",
        version="dev",
        mount="api/python",
        out=str(out),
        repo_root=str(tmp_path),
        docstring_style="google",
    )
    em = Emitter(cfg)
    stats = em.run()
    return {
        "out": out,
        "stats": stats,
        "inventory": json.loads((out / "inventory.python.json").read_text()),
        "index_mdx": (out / "mypkg" / "index.mdx").read_text(),
        "core_mdx": (out / "mypkg" / "core.mdx").read_text(),
    }


def test_pages_written(emitted):
    out: Path = emitted["out"]
    assert (out / "mypkg" / "index.mdx").is_file()  # package __init__ -> index
    assert (out / "mypkg" / "core.mdx").is_file()  # plain module -> <name>.mdx
    assert (out / "inventory.python.json").is_file()


def test_frontmatter(emitted):
    mdx = emitted["core_mdx"]
    assert mdx.startswith("---\n")
    assert 'title: "mypkg.core"' in mdx
    assert "language: python" in mdx
    assert 'fqName: "mypkg.core"' in mdx
    assert 'apiVersion: "dev"' in mdx
    assert 'sourceRepo: "owner/repo"' in mdx
    assert 'sourceRef: "v1.0"' in mdx
    # description comes from the module summary (first paragraph).
    assert 'description: "Core module."' in mdx


def test_auto_generated_banner(emitted):
    assert (
        "{/* AUTO-GENERATED by bloqade-docs-emit-python. Do not edit by hand. */}"
        in emitted["core_mdx"]
    )


def test_module_component(emitted):
    mdx = emitted["core_mdx"]
    assert "<ApiModule" in mdx
    assert 'name="core"' in mdx
    assert 'fqName="mypkg.core"' in mdx
    assert "</ApiModule>" in mdx


def test_function_component_and_signature(emitted):
    mdx = emitted["core_mdx"]
    assert "<ApiFn" in mdx
    assert 'name="greet"' in mdx
    assert 'fqName="mypkg.core.greet"' in mdx
    assert 'kind="function"' in mdx
    assert (
        '<Signature lang="python" code={`def greet(name: str, times: int = 1) -> str`} />'
        in mdx
    )
    # Params table with the two documented parameters.
    assert "<Params" in mdx
    assert "name: 'name'," in mdx
    assert "name: 'times'," in mdx
    # Returns + Raises derived from the Google docstring sections.
    assert '<Returns type="str"' in mdx
    assert "<Raises" in mdx
    assert "type: 'ValueError'," in mdx


def test_private_members_excluded(emitted):
    mdx = emitted["core_mdx"]
    assert "_hidden" not in mdx
    assert "_secret" not in mdx


def test_class_component(emitted):
    mdx = emitted["core_mdx"]
    assert "<ApiClass" in mdx
    assert 'name="Widget"' in mdx
    assert 'fqName="mypkg.core.Widget"' in mdx
    # Constructor signature drops `self` and includes the __init__ params.
    assert '<Signature lang="python" code={`class Widget(size: int)`} />' in mdx
    # Attributes table (from the class docstring Attributes section).
    assert '<Params title="Attributes"' in mdx
    assert "name: 'size'," in mdx


def test_method_and_property_kinds(emitted):
    mdx = emitted["core_mdx"]
    assert 'fqName="mypkg.core.Widget.area"' in mdx
    assert 'kind="method"' in mdx
    assert 'fqName="mypkg.core.Widget.doubled"' in mdx
    assert 'kind="property"' in mdx
    # Property signature is `name: annotation`, not a def.
    assert '<Signature lang="python" code={`doubled: int`} />' in mdx


def test_module_attributes_table(emitted):
    # A module-level constant becomes an Attributes row.
    mdx = emitted["core_mdx"]
    assert '<Params title="Attributes"' in mdx
    assert "name: 'GREETING'," in mdx


def test_inventory_entries(emitted):
    inv = emitted["inventory"]
    by_fq = {e["fqName"]: e for e in inv}

    # Module entry: S = M, anchor is the module fqName.
    assert by_fq["mypkg.core"] == {
        "fqName": "mypkg.core",
        "kind": "module",
        "url": "/api/python/mypkg/core/#mypkg.core",
    }
    # Function.
    assert by_fq["mypkg.core.greet"] == {
        "fqName": "mypkg.core.greet",
        "kind": "function",
        "url": "/api/python/mypkg/core/#mypkg.core.greet",
    }
    # Class + method + property with the right kinds.
    assert by_fq["mypkg.core.Widget"]["kind"] == "class"
    assert (
        by_fq["mypkg.core.Widget"]["url"] == "/api/python/mypkg/core/#mypkg.core.Widget"
    )
    assert by_fq["mypkg.core.Widget.area"]["kind"] == "method"
    assert by_fq["mypkg.core.Widget.doubled"]["kind"] == "property"

    # Private members never reach the inventory.
    assert not any(".Widget._secret" in fq for fq in by_fq)
    assert not any(fq.endswith("._hidden") for fq in by_fq)


def test_inventory_urls_follow_derivation_rule(emitted):
    # url == /<mount>/<module-path>/#<fqName> for every entry on this page.
    for entry in emitted["inventory"]:
        assert entry["url"].startswith("/api/python/mypkg/")
        assert entry["url"].endswith("#" + entry["fqName"])


def test_stats(emitted):
    stats = emitted["stats"]
    # Root package (mypkg) + core module.
    assert stats.modules_emitted == 2
    assert stats.symbols >= 5  # module, greet, Widget, area, doubled, attrs...
