#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""gen_compat_matrix.py — regenerate the Bloqade compatibility-matrix page.

The ``bloqade`` meta-package is a thin distribution that pins a compatible set
of sub-packages (``bloqade-circuit``, ``bloqade-analog``, ``bloqade-lanes``,
``bloqade-tsim``). This script turns those pins into a Markdown table:

    | bloqade | bloqade-circuit | bloqade-analog | bloqade-lanes | bloqade-tsim |

and writes it to ``src/content/docs/api/compatibility.mdx``.

ROWS ("one per known bloqade version") come from, in order of precedence:

  1. ``--extra PATH`` — an optional TOML file of historical rows, so older
     released matrices survive a regenerate. Shape::

         [[row]]
         bloqade = "0.34"
         bloqade-circuit = "0.13.0"
         bloqade-analog  = "0.16.0"
         bloqade-lanes   = "0.9.0"
         bloqade-tsim    = "0.1.3"

  2. the current line, parsed from ``pyproject.toml`` (``[project].version`` +
     the ``bloqade-*~=X.Y.Z`` dependency pins). This is the ``dev`` / newest
     release row and is always emitted (unless ``--no-pyproject``).

Run::

    uv run website/scripts/gen_compat_matrix.py
    python website/scripts/gen_compat_matrix.py --pyproject ../pyproject.toml
"""

from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
WEBSITE_DIR = SCRIPT_DIR.parent
REPO_ROOT = WEBSITE_DIR.parent
DEFAULT_PYPROJECT = REPO_ROOT / "pyproject.toml"
DEFAULT_OUT = WEBSITE_DIR / "src" / "content" / "docs" / "api" / "compatibility.mdx"

# Sub-packages tracked in the matrix (column order).
SUBPACKAGES = ["bloqade-circuit", "bloqade-analog", "bloqade-lanes", "bloqade-tsim"]

# "bloqade-circuit[cirq,stim]~=0.14.1" -> name="bloqade-circuit", spec="~=0.14.1"
DEP_RE = re.compile(r"^\s*(?P<name>[A-Za-z0-9_.-]+)\s*(?:\[[^\]]*\])?\s*(?P<spec>.*)$")


def parse_pyproject(pyproject: Path) -> tuple[str, dict[str, str]]:
    """Return (meta_version, {subpackage: version}) from pyproject dependencies."""
    with pyproject.open("rb") as fh:
        data = tomllib.load(fh)
    project = data.get("project", {})
    meta_version = str(project.get("version", "dev"))
    pins: dict[str, str] = {}
    for dep in project.get("dependencies", []):
        m = DEP_RE.match(dep)
        if not m:
            continue
        name = m.group("name")
        if name not in SUBPACKAGES:
            continue
        spec = m.group("spec").strip()
        # Extract the bare version out of the specifier (~=0.14.1 -> 0.14.1).
        ver = re.sub(r"^[~=<>!^ ]+", "", spec).split(",")[0].strip()
        pins[name] = ver or spec or "-"
    return meta_version, pins


def meta_label(version: str) -> str:
    """`0.35.0-dev` -> `0.35` (the release line the dev tracks); `0.34.1` -> `0.34`."""
    m = re.match(r"^v?(\d+)\.(\d+)", version)
    return f"{m.group(1)}.{m.group(2)}" if m else version


def load_extra_rows(path: Path | None) -> list[dict[str, str]]:
    if path is None or not path.is_file():
        return []
    with path.open("rb") as fh:
        data = tomllib.load(fh)
    return list(data.get("row", []))


def sem_key(version: str) -> list[int]:
    return [int(n) for n in re.findall(r"\d+", version)]


def render_table(rows: list[dict[str, str]]) -> list[str]:
    header = ["bloqade", *SUBPACKAGES]
    lines = ["| " + " | ".join(f"`{h}`" for h in header) + " |"]
    lines.append("|" + "|".join([" --- "] * len(header)) + "|")
    for row in rows:
        cells = [f"**{row.get('bloqade', '-')}**"]
        for pkg in SUBPACKAGES:
            val = row.get(pkg, "-")
            cells.append(f"`{val}`" if val and val != "-" else "-")
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def build_page(rows: list[dict[str, str]], dev_label: str | None) -> str:
    front = [
        "---",
        "title: Compatibility matrix",
        'description: "Which bloqade-* sub-package versions each bloqade meta-version pins."',
        "---",
        "",
        "{/* GENERATED by website/scripts/gen_compat_matrix.py — do not edit by hand. */}",
        "",
        "The `bloqade` meta-package pins a compatible set of sub-packages. Each row",
        "below is one released `bloqade` version and the sub-package versions it",
        "installs. `pip install bloqade==<version>` resolves to that row.",
        "",
    ]
    body = render_table(rows)
    notes = [
        "",
    ]
    if dev_label:
        notes += [
            f"The **{dev_label}** row is the current development line (tracked by the",
            "`dev` docs); released versions are cut from it. Version pins are the",
            "lower bounds from the meta-package's `~=` requirements.",
            "",
        ]
    return "\n".join(front + body + notes) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--pyproject",
        type=Path,
        default=DEFAULT_PYPROJECT,
        help="Path to pyproject.toml.",
    )
    ap.add_argument(
        "--extra", type=Path, default=None, help="Optional TOML of historical rows."
    )
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output MDX path.")
    ap.add_argument(
        "--no-pyproject", action="store_true", help="Do not add the pyproject row."
    )
    args = ap.parse_args(argv)

    rows: list[dict[str, str]] = list(load_extra_rows(args.extra))
    dev_label: str | None = None

    if not args.no_pyproject:
        if not args.pyproject.is_file():
            ap.error(f"pyproject not found: {args.pyproject}")
        meta_version, pins = parse_pyproject(args.pyproject)
        dev_label = meta_label(meta_version)
        row = {"bloqade": dev_label}
        row.update(pins)
        # De-dupe: pyproject row wins over any same-label extra row.
        rows = [r for r in rows if r.get("bloqade") != dev_label]
        rows.append(row)

    # Newest meta-version first.
    rows.sort(key=lambda r: sem_key(r.get("bloqade", "0")), reverse=True)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_page(rows, dev_label), encoding="utf-8")
    print(f"[compat] wrote {args.out} ({len(rows)} row(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
