/**
 * vitest global setup — hermeticity safety net for the GENERATED inventory.
 *
 * `src/lib/xref.ts` has a static `import inventory from
 * '../generated/xref-inventory.json'`. That file is GITIGNORED and generated by
 * the build (`build_inventory.mjs` / the xref integration), so on a fresh clone
 * — or in the fast `docs:unit` CI step that does NOT run a full build — it can
 * be ABSENT, which would make the static import (and therefore importing
 * xref.ts at all) fail to resolve.
 *
 * So here we ensure the file EXISTS with a minimal empty-but-valid shape, but
 * ONLY when it is missing — we never overwrite a real, already-generated
 * inventory. The unit tests do NOT depend on this stub's CONTENT: `xref.test.ts`
 * `vi.mock`s the JSON module with a controlled fixture, and `ApiXref.test.ts`
 * `vi.mock`s `@/lib/xref` entirely, so resolution is deterministic regardless of
 * whether the on-disk file is the stub or a real multi-MB inventory. This setup
 * only guarantees the module *resolves*.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const inventoryPath = resolve(here, '../../src/generated/xref-inventory.json');

export default function setup() {
  if (!existsSync(inventoryPath)) {
    mkdirSync(dirname(inventoryPath), { recursive: true });
    // Minimal valid XrefInventory shape ({ byVersion, any }); content is
    // irrelevant because tests mock resolution.
    writeFileSync(inventoryPath, JSON.stringify({ byVersion: {}, any: {} }));
  }
}
