authors:
  jwurtz:
    name: Jonathan Wurtz
    description: Quantum Solutions Lead
    avatar: https://media.licdn.com/dms/image/v2/C4D03AQGgTNZKZcfglw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1621114965360?e=1746057600&v=beta&t=gRZ2RIKiU9uFLRcn0LvXJuHaNLJLjH7c2h0YFXgZsO0
    url: https://www.linkedin.com/in/jonathan-wurtz-7a4855181/
  rogerluo:
    name: Xiuzhe (Roger) Luo
    description: I cast quantum spells.
    avatar: https://github.com/Roger-luo.png
    url: https://rogerluo.dev
  weinbe58:
    name: Phillip Weinberg
    description: I build Classical and Quantum software.
    avatar: https://github.com/weinbe58.png
    url: https://github.com/weinbe58
  kaihsin:
    name: Kai-Hsin Wu
    description: Scientific Software Engineer
    avatar: https://github.com/kaihsin.png
    url: https://github.com/kaihsin
  johnzl-777:
    name: John Long
    description: Scientific Software Developer
    avatar: https://github.com/johnzl-777.png
    url: https://github.com/johnzl-777
