/**
 * xref.ts — build-time API cross-reference resolver.
 *
 * Phase C1. Turns a fully-qualified id (as passed to <ApiXref to="...">) into a
 * real page URL + anchor, using the merged inventory generated by
 * `website/scripts/build_inventory.mjs` (also regenerated by the xref
 * integration at astro:config:setup).
 *
 * The generated JSON is a plain lookup so this resolves synchronously at build
 * time (and during `astro dev`) with no async / network work:
 *
 *   {
 *     "byVersion": { "<apiVersion>": { "<fqName>": "<url>" } },
 *     "any":       { "<fqName>": "<url>" }   // version-agnostic fallback
 *   }
 */
import inventory from '../generated/xref-inventory.json';

interface XrefInventory {
  byVersion: Record<string, Record<string, string>>;
  any: Record<string, string>;
}

const inv = inventory as XrefInventory;

/**
 * Resolve a fully-qualified id to its target URL (page path + `#fqName`).
 *
 * Resolution prefers the SAME apiVersion as the referring page, then falls
 * back to the version-agnostic map. Returns `null` when unknown so callers can
 * flag the reference as unresolved.
 *
 * @param to      the fully-qualified id, e.g. "bloqade.task.BatchFuture.result"
 * @param version the referring page's apiVersion, e.g. "dev" or "0.35"
 */
export function resolveXref(to: string, version?: string): string | null {
  if (version) {
    const byVersion = inv.byVersion?.[version];
    if (byVersion && byVersion[to]) return byVersion[to];
  }
  if (inv.any && inv.any[to]) return inv.any[to];
  return null;
}

/** True when `to` resolves (either for `version` or the agnostic fallback). */
export function hasXref(to: string, version?: string): boolean {
  return resolveXref(to, version) !== null;
}
