name: Documentation (preview)
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    name: Deploy preview documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install Documentation dependencies
        run: uv sync --group doc

      - name: extract bloqade-circuit version
        id: bloqade_circuit_extract_version
        run: |
          VERSION=$(uv pip show bloqade-circuit | awk '/^Version: / {print "v"$2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: clone the latest bloqade-circuit release
        id: clone_bloqade_circuit
        uses: actions/checkout@v5
        with:
          repository: QuEraComputing/bloqade-circuit
          path: 'submodules/bloqade-circuit'
          ref: ${{ steps.bloqade_circuit_extract_version.outputs.version }}

      - name: Extract bloqade-analog version
        id: bloqade_analog_extract_version
        run: |
          VERSION=$(uv pip show bloqade-analog | awk '/^Version: / {print "v"$2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: clone the latest bloqade-analog release
        id: clone_bloqade_analog
        uses: actions/checkout@v5
        with:
          repository: QuEraComputing/bloqade-analog
          path: 'submodules/bloqade-analog'
          ref: ${{ steps.bloqade_analog_extract_version.outputs.version }}

      - name: Set up build cache
        uses: actions/cache@v4
        id: cache
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Depoly documentation
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          uv run mkdocs build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site
